spring.application.name=url-shortner

# -------------------------------------------------------------
# DATABASE CONNECTION PROPERTIES
# -------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/url-shortner
spring.datasource.username=postgres
spring.datasource.password=shubham
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------------------------------------
# SPRING DATA JPA / HIBERNATE PROPERTIES
# -------------------------------------------------------------
# Automatically validates, creates, updates, or drops the schema on application startup.
# Options: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update

# Explicitly specifies the dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -------------------------------------------------------------
# LOGGING / DEBUGGING (Optional)
# -------------------------------------------------------------
# Prints SQL statements to the console
spring.jpa.show-sql=true
# Formats the printed SQL statements for readability
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

